### PR TITLE
2 to 1 line

### PR DESCRIPTION
**Pull request by FayasNoushad**
One line is better

### CODE REVIEW

**Comment by tomgross** [comment]
Hi @FayasNoushad thanks for contributing but this does not follow PEP8 (see https://www.python.org/dev/peps/pep-0008/#imports)

**Comment by FayasNoushad** [comment]
Screenshot

It's correct 🤔

**Comment by tomgross** [comment]
You are right, it is possible. I still prefer every import on a separate line. So I have not to think of exceptions from the general rule ;-). Also it makes it easier to copy&paste these lines and to remove if obsolete.

**Comment by FayasNoushad** [comment]
> You are right, it is possible. I still prefer every import on a separate line. So I have not to think of exceptions from the general rule ;-). Also it makes it easier to copy&paste these lines and to remove if obsolete.

Ok

**Pull request closed without merging**
